<?php 
/*
Plugin Name: Automate sending digital keys
Plugin URI: https://github.com/inmass/automate-sending-digital-keys
Description: Automate sending digital keys
Version: 1.0.0
Author: iinmass
Author URI: https://iinmass.com
Text Domain: asdk
Generated By: http://ensuredomains.com
*/

function asdk_callback()
{
    // add non admin pages to redirect to another page

    add_menu_page( "ASDK", "ASDK", "", "auto-send-activation-keys", "","dashicons-admin-network", 4);
    add_submenu_page("auto-send-activation-keys", "ASDK Home", "ASDK Home", "manage_options", "asdk-home", "asdk_home");
    add_submenu_page("auto-send-activation-keys","Activation keys","Activation keys","manage_options","activation-keys","activation_keys");
    add_submenu_page("auto-send-activation-keys","Add new key","Add new key","manage_options","add-key","add_key");
    add_submenu_page("auto-send-activation-keys","Keys types","Keys types","manage_options","keys-types","keys_types");
    add_submenu_page("auto-send-activation-keys","Add new key type","Add new key type","manage_options","add-key-type","add_key_type");
}

add_action("admin_menu","asdk_callback");




function asdk_home()
{
    include "includes/home.php";
}

function activation_keys()
{
    include "includes/activation_keys.php";
}

function add_key()
{
    include "includes/add_key.php";
}

function keys_types()
{
    include "includes/keys_types.php";
}

function add_key_type()
{
    include "includes/add_key_type.php";
}






//////////////////////////////////////////////////
register_activation_hook(__FILE__,"createtable");
register_activation_hook(__FILE__,"createtable_sec");
register_activation_hook(__FILE__,"createtable_third");
function createtable()
{
    # code...
    
    global $wpdb;
    $plugin_name_db_version = '1.0.0';
    $table_name = $wpdb->prefix . "asdk_keys";
    $charset_collate = $wpdb->get_charset_collate();

    $sql = "CREATE TABLE $table_name (
                id mediumint(9) NOT NULL AUTO_INCREMENT PRIMARY KEY,
                activation_key varchar(255) NULL UNIQUE,
                key_type varchar(255) NULL,
                key_count int(11) NULL,
                used BIT DEFAULT 0 NOT NULL
            ) $charset_collate;";
    
    // $wpdb->query($sql);
    require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
    dbDelta($sql);
}

function createtable_sec()
{
    # code...
    
    global $wpdb;
    $plugin_name_db_version = '1.0.0';
    $table_name = $wpdb->prefix . "asdk_keys_users"; 
    $charset_collate = $wpdb->get_charset_collate();

    $sql = "CREATE TABLE $table_name (
            id mediumint(9) NOT NULL AUTO_INCREMENT PRIMARY KEY,
            activation_key varchar(255) NULL,
            key_type varchar(255) NULL,
            sent_to varchar(255) NULL NULL,
            sell_date DATETIME NULL
        ) $charset_collate;";

    require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
    dbDelta($sql);
}
function createtable_third()
{
    # code...
    
    global $wpdb;
    $plugin_name_db_version = '1.0.0';
    $table_name = $wpdb->prefix . "asdk_keys_types"; 
    $charset_collate = $wpdb->get_charset_collate();
    
    
    $sql = "CREATE TABLE $table_name (
            id mediumint(9) NOT NULL AUTO_INCREMENT PRIMARY KEY,
            title varchar(255) NULL UNIQUE
        ) $charset_collate;";

    require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
    dbDelta($sql);
    // add two rows to the table if table is empty
    if($wpdb->get_var("SELECT COUNT(*) FROM $table_name") == 0) {
        $wpdb->insert($table_name, array('title' => 'WINDOWS10PRO'));
        $wpdb->insert($table_name, array('title' => 'WINDOWS10FAMILY'));
        $wpdb->insert($table_name, array('title' => 'OFFICE2021PRO'));
    }
    
}





// add woocommerce product hooks
// The code for displaying WooCommerce Product Custom Fields
add_action( 'woocommerce_product_options_general_product_data', 'woocommerce_product_custom_fields' ); 
// Following code Saves  WooCommerce Product Custom Fields
add_action( 'woocommerce_process_product_meta', 'woocommerce_product_custom_fields_save' );

function woocommerce_product_custom_fields () {
    global $woocommerce, $post, $wpdb;
    echo '<div class=" product_custom_field ">';

    $keys_types_table = $wpdb->prefix."asdk_keys_types";
    $keys_types_query = $wpdb->get_results("SELECT `title` FROM $keys_types_table");
    $keys_types = array(
        '' => 'Select key type'
    );
    foreach ($keys_types_query as $keys_type) {
        $keys_types[$keys_type->title] = $keys_type->title;
    }

    woocommerce_wp_select(
        array(
            'id' => '_asdk_product_type',
            'placeholder' => 'ASDK product type',
            'label' => __('ASDK product type', 'woocommerce'),
            'options' => $keys_types
        )
    );
    
    echo '<a href="'. admin_url("admin.php?page=add-key-type") .'" style="margin-left: 10px;">Add new key type</a>';

    echo '</div>';
}

function woocommerce_product_custom_fields_save($post_id)
{
    // Custom Product Text Field
    $woocommerce_asdk_product_type = $_POST['_asdk_product_type'];
    if (!empty($woocommerce_asdk_product_type))
        update_post_meta($post_id, '_asdk_product_type', esc_attr($woocommerce_asdk_product_type));
}


// add woocommerce orders hooks


// delete plugin
function dropTables()
{
    global $wpdb;
    # code...
    require(ABSPATH . 'wp-admin/includes/upgrade.php');

    $table_name = $wpdb->prefix . "asdk_keys";
    $sql = "DROP TABLE IF EXISTS $table_name";
    $wpdb->query($sql);
    $table_name = $wpdb->prefix . "asdk_keys_types";
    $sql = "DROP TABLE IF EXISTS $table_name";
    $wpdb->query($sql);
    $table_name = $wpdb->prefix . "asdk_keys_users";
    $sql = "DROP TABLE IF EXISTS $table_name";
    $wpdb->query($sql);

}

register_uninstall_hook(__FILE__,"dropTables");
